import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from './providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Tiar',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} text-white bg-white dark:bg-gradient-to-t dark:from-[#161e1b] dark:to-[#041c23] antialiased`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
