export { default as reactIcon } from './reactjs.svg'
export { default as nextIcon } from './nextjs.svg'
export { default as typescriptIcon } from './typescript.svg'
export { default as graphqlIcon } from './graphql.svg'
export { default as sassIcon } from './sass.svg'
export { default as tailwindIcon } from './tailwind.svg'
export { default as reactIconColor } from './reactcolor.svg'
export { default as sassIconColor } from './sasscolor.svg'
export { default as tailwindIconColor } from './tailwindcolor.svg'
export { default as typescriptIconColor } from './typescriptcolor.svg'
export { default as graphqlIconColor } from './gqlcolor.svg'
export { default as nextIconColor } from './nextcolor.svg'

